### ISSUE TITLE
downgrade instead of upgrade

### ISSUE THREAD

**Issue by dominix** [phil-opp/cargo-update-installed#1]
Hi everyone, 
its looks I am the only one to use this wonderful tool :-) 
When I launch cargo-update-installed the program run fine and upgrade some installed tools, 
but when it comes to broot, it tries to downgrade it

`cargo-update-installed
    Updating crates.io index
Up to date: bandwhich 0.20.0
Up to date: bat 0.20.0
Up to date: cargo-update-installed 0.1.2
Up to date: exa 0.10.1
Up to date: gping 1.3.0
Up to date: htmlq 0.4.0
Up to date: mdcat 1.1.1
Up to date: sniffnet 1.1.2

Updating broot from 1.21.1 to 1.13.1
    Updating crates.io index
  Installing broot v1.13.1
   Compiling autocfg v1.1.0
   Compiling libc v0.2.140
...
`
we can see clearly that I have broot 1.21.1 and it tries to "upgrade" to 1.13.1 
however broot install successfully at the last version, I have uninstalled it and reinstalled it with no problems.

NB: I have installed the same tools on some other machine and I got the same problem with a funny variant,
`
cargo-update-installed 
    Updating crates.io index
Up to date: bandwhich 0.20.0
Up to date: bat 0.23.0
Up to date: cargo-update-installed 0.1.2
Up to date: du-dust 0.8.5
Up to date: htmlq 0.4.0
Up to date: mdcat 1.1.1
Up to date: sniffnet 1.1.2
Up to date: syncfast 0.2.0

Updating broot from 1.21.1 to 0.12.2
  Downloaded broot v0.12.2
  Downloaded 1 crate (1.6 MB) in 3.22s
    Updating crates.io index
  Installing broot v0.12.2
...
`
here it tries to change version it downgrade to : 0.12.2 instead of the previous 1.13.1 and instead of the original 1.21.1 that is current.

NB : installed on a third machine with same effet, and this times it tries to downgrade to 0.12.2. 

cheers from Tahiti.

**Comment by phil-opp** [comment]
Hi @dominix, great to hear that you this crate is useful to you! Thanks a lot for reporting this issue, this is clearly a bug. I opened a PR at #2 to fix this.

You might also be interested in https://github.com/rust-lang/cargo/issues/9527, which proposes to integrate this functionality into cargo itself.
