### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by overtube** [phil-opp/cargo-update-installed#4]
Hi,I have question about that: 
```
./cargo update-installed 
Warning: Git binaries are not supported. Ignoring `artichoke`.
Warning: Git binaries are not supported. Ignoring `shipp`.
Updating `aipman`
    Updating crates.io index
     Ignored package `aipman v11.0.0` is already installed, use --force to override
```
I already remove that first 2 (artichoke, shipp) binaries but check. It does not matter, that 2 names in checklist, ho remove from fetch list that

**Comment by overtube** [comment]
and also I removed all `/tmp content and .cargo/git .cargo/registry` content but nothing changed and also I use cargo-trim for that, but cant help too

**Comment by overtube** [comment]
but after removing that: 
```
rm -rf registry .tauri-mobile .package-cache .crates2.json .crates.toml .cargo-mobile2 .package-cache-mutate
```
any cargo bin don't worked anymore :) so what need to do?

**Comment by overtube** [comment]
after reintalling system cargo don't help lol

**Comment by overtube** [comment]
but files take in place again

**Comment by phil-opp** [comment]
Just to clarify: You want to remove the warnings about `artichoke` and `shipp`? 

If you don't need these binaries anymore, you can run `cargo uninstall artichoke` and `cargo uninstall shipp`. Does this help?

**Comment by overtube** [comment]
ofc, but after make `cargo uninstall artichoke shipp`, binaries deleted sucsessfully, and all done and nice, but after run `cargo-update-installed` the programs are still on the list and yes they are not present in crates.io that is installed using `cargo --git` command. And yes, it also says that updates from Git are not supported. So everything is probably fine and that’s exactly how it should be. Just Cargo pkg manager case

**Comment by phil-opp** [comment]
Are the two binaries still listed in `cargo install --list` after uninstalling?

**Comment by overtube** [comment]
already not, because recompilation all binaries already maked, and all fixed :) so, after all binaries on place as well, also that files worked perfect well if run him's from dir with ./somebinary. But before if just run name somebinary from just terminal as normal app nothing happen, after recompilation that fixed. Just some strange cargo behavor :) Your App very great, thx ❤

**Comment by overtube** [comment]
and now all worked well ❤ sorry for worry.
