### ISSUE TITLE
Question 2

### ISSUE THREAD

**Issue by overtube** [phil-opp/cargo-update-installed#5]
How add all executable binaries from `.cargo/bin` to fetch list for make propperly work `./cargo-update-installed` again.
I won't recompile all that binaries for just make workin one but nice utility

**Comment by overtube** [comment]
pls help

**Comment by phil-opp** [comment]
We're just parsing the output of `cargo install --list`. I'm not sure what kind of metadata files cargo uses to store which binaries are installed.

**Comment by overtube** [comment]
thx for respond and help, but as maybe I I'm right undestand, need just put - output from `cargo install --list` command in `crates.toml`

But after if output that command is empty. no one binary, but on `.cargo/bin` have a lot.
Only if I make force recompile: `cargo install some-app --force`
binaries become visible after executing this command: `cargo install --list` but anyway I just make recompile all of mine binaries, I think that is better, than stupid and borring filling `crates.toml` on `.cargo` dir. Lol I use from `.cargo/bin` dir `ls -w 10000 -C . | head` with deleteting some not needed spaces and pass cargo install --force for names on that list

**Comment by overtube** [comment]
U write and make realy great, nice and usefull app! REALY thx for your work! , that issue not about your great app, just about some strange behavior of the `cargo` packet manager. 
Probably for now the best thing I can do is a feedback

**Comment by overtube** [comment]
Just strange `cargo` package manager behavor

**Comment by overtube** [comment]
and recompile almost done, lol
